
title: Josh Feldstein
email: jfeldstein30@mtlsd.net
description: >- # this means to ignore newlines until "baseurl:"
  Journalism by HS Senior Josh Feldstein.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
theme: jekyll-whiteglass
#theme: minima
#plugins:
#  - jekyll-feed
plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-paginate


permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5000

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
